### ISSUE TITLE
Create a galactic branch to address minor package differences

### ISSUE THREAD

**Issue by Chrislai502** [linklab-uva/RACECAR_DATA#7]
Suggesting the creation of a separate branch called "galactic" to address versioning issues related to ROS packages. 
Specifically, a modification in the file racecar_utils/src/odom_to_tf.cpp, changing the include directive:

`tf2_eigen/tf2_eigen.hpp`
to 
`tf2_eigen/tf2_eigen.h `

for ros2 galactic.

**Comment by sisaha9** [comment]
Addressing in this PR: https://github.com/linklab-uva/RACECAR_DATA/pull/8

At least for this specific change allows to have one branch for both

**Comment by amarkoolk** [comment]
Thanks for the change @sisaha9! Looks good will merge :+1:
